In [7]:
import pandas as pd
import numpy as np

In [2]:
students=pd.DataFrame({
   "name":["riya","shreya","kashi"],
    "age":[21,18,20],
    "marks":[90,40,45]
})
print(students)

     name  age  marks
0    riya   21     90
1  shreya   18     40
2   kashi   20     45

In [3]:
#from dictionary of list
student={
   "name":["riya","shreya","kashi"],
    "age":[21,18,20],
    "marks":[90,40,45]
}
# print(pd.DataFrame(student))

     name  age  marks
0    riya   21     90
1  shreya   18     40
2   kashi   20     45

In [5]:
#from list of list
data = [
    ["Riya", 22, 90],
    ["Rahul", 23, 85],
    ["Amit", 24, 95]
]
df=pd.DataFrame( data,columns=["name","marks","age"])
print(df)

    name  marks  age
0   Riya     22   90
1  Rahul     23   85
2   Amit     24   95

In [6]:
#from list of dictionaries
data = [
    {"Name":"Riya","Age":22,"Marks":90},
    {"Name":"Rahul","Age":23,"Marks":85},
    {"Name":"Amit","Age":24,"Marks":95}
]

df = pd.DataFrame(data)

print(df)

    Name  Age  Marks
0   Riya   22     90
1  Rahul   23     85
2   Amit   24     95

In [8]:
#from numpy array
arr=np.array([[1,2],[3,4],[5,6]])
df=pd.DataFrame(arr,columns=["A","B"])
print(df)

   A  B
0  1  2
1  3  4
2  5  6

In [9]:
#from series
name=pd.Series(["riya","shreya","kashi"])
age=pd.Series([22,23,24])
df=pd.DataFrame({
    "Name":name,
    "age":age
})
print(df)

     Name  age
0    riya   22
1  shreya   23
2   kashi   24

In [12]:
#empty array
df=pd.DataFrame()
print(df)

Empty DataFrame
Columns: []
Index: []

In [26]:
#custom index
data={
    "Name":["riya","shreeya","kashi"],
    "age":[22,23,24]
}
df=pd.DataFrame(
    data,
    index=["A","B","C"]
)
print(df)
print(df.shape)
print(df.size)
print(df.ndim)
print(df.columns)
print("")
print(df.index) #return index
print(df.values)
print(df.dtypes) #return data type of each column
print("")
print(df.axes) #return row and column axis
print(df.empty) #checks whether df is empty or not
print(df.T)

      Name  age
A     riya   22
B  shreeya   23
C    kashi   24
(3, 2)
6
2
Index(['Name', 'age'], dtype='object')

Index(['A', 'B', 'C'], dtype='object')
[['riya' 22]
 ['shreeya' 23]
 ['kashi' 24]]
Name    object
age      int64
dtype: object

[Index(['A', 'B', 'C'], dtype='object'), Index(['Name', 'age'], dtype='object')]
False
         A        B      C
Name  riya  shreeya  kashi
age     22       23     24

In [51]:
#understanding and inspecting dataframe
data={
    "Name":["Riya","rahul","Amit","priya","Neha","sonu"],
    "age":[22,25,24,23,26,27],
    "Salary": [35000, 42000, 50000, 45000, 55000,54000],
    "Department": ["AI", "HR", "Finance", "Marketing", "AI","AI"]
}
df=pd.DataFrame(data)
# print(df)
print(df.head())#print first 5 rows by default
print("")
print(df.head(2)) #custom call
print("")
print(df.tail()) #print last 5 rows by default
print("")
print(df.tail(2))
print("")
print(df.sample()) #print random row
print("")
print(df.sample(2))
print("")
print(df.sample(3,random_state=32))
print(df.info()) #gives information like how many entries,rows,columns
print(df.describe()) #generate summary stastics for numeric column
print(df.describe(include="all")) #includes categorial column to
print(df.count())#count non missing values
print(df.nunique()) # count number of unique values
print(df["Department"].value_counts()) #count values usually applied to single column
print(df.memory_usage())# shows memory used by each column

    Name  age  Salary Department
0   Riya   22   35000         AI
1  rahul   25   42000         HR
2   Amit   24   50000    Finance
3  priya   23   45000  Marketing
4   Neha   26   55000         AI

    Name  age  Salary Department
0   Riya   22   35000         AI
1  rahul   25   42000         HR

    Name  age  Salary Department
1  rahul   25   42000         HR
2   Amit   24   50000    Finance
3  priya   23   45000  Marketing
4   Neha   26   55000         AI
5   sonu   27   54000         AI

   Name  age  Salary Department
4  Neha   26   55000         AI
5  sonu   27   54000         AI

    Name  age  Salary Department
3  priya   23   45000  Marketing

   Name  age  Salary Department
4  Neha   26   55000         AI
2  Amit   24   50000    Finance

    Name  age  Salary Department
5   sonu   27   54000         AI
1  rahul   25   42000         HR
0   Riya   22   35000         AI
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      object
 1   age         6 non-null      int64
 2   Salary      6 non-null      int64
 3   Department  6 non-null      object
dtypes: int64(2), object(2)
memory usage: 324.0+ bytes
None
             age        Salary
count   6.000000      6.000000
mean   24.500000  46833.333333
std     1.870829   7678.975626
min    22.000000  35000.000000
25%    23.250000  42750.000000
50%    24.500000  47500.000000
75%    25.750000  53000.000000
max    27.000000  55000.000000
        Name        age        Salary Department
count      6   6.000000      6.000000          6
unique     6        NaN           NaN          4
top     Riya        NaN           NaN         AI
freq       1        NaN           NaN          3
mean     NaN  24.500000  46833.333333        NaN
std      NaN   1.870829   7678.975626        NaN
min      NaN  22.000000  35000.000000        NaN
25%      NaN  23.250000  42750.000000        NaN
50%      NaN  24.500000  47500.000000        NaN
75%      NaN  25.750000  53000.000000        NaN
max      NaN  27.000000  55000.000000        NaN
Name          6
age           6
Salary        6
Department    6
dtype: int64
Name          6
age           6
Salary        6
Department    4
dtype: int64
Department
AI           3
HR           1
Finance      1
Marketing    1
Name: count, dtype: int64
Index         132
Name           48
age            48
Salary         48
Department     48
dtype: int64

In [70]:
data={
    "Name":["Riya","rahul","Amit","priya","Neha","sonu"],
    "age":[22,25,24,23,26,27],
    "Salary": [35000, 42000, 50000, 45000, 55000,54000],
    "Department": ["AI", "HR", "Finance", "Marketing", "AI","AI"]
}
df=pd.DataFrame(data)
print(df["Name"]) #selecting column
print(type(df["Name"]))
print(df[["Name","Salary"]]) #selecting multiple column
print(df.columns) #give column name
print(df.loc[2]) #select row using label
print(type(df.loc[2]))
print(df.loc[[1,3]])
print(df.loc[1:3]) #give 1,2,3 row 
print(df.loc[2,"Name"]) #select column using label it give 2nd row name
print(df.loc[:,["Name","Salary"]]) #select multiple column and all rows data of that column
print(df.loc[[1,3],["Name","Salary"]])
print(df.iloc[2]) #works with integer position (row-3)
print(df.iloc[2,1]) #gives name at row 3 and column 2 position that is amit
print(df.iloc[:,[1,3]])
print(df.iloc[[1,3],[1,3]])
print(df.iloc[1:4,1:4])
print(df.iloc[1:4])
print(df.loc[1:4])

0     Riya
1    rahul
2     Amit
3    priya
4     Neha
5     sonu
Name: Name, dtype: object
<class 'pandas.core.series.Series'>
    Name  Salary
0   Riya   35000
1  rahul   42000
2   Amit   50000
3  priya   45000
4   Neha   55000
5   sonu   54000
Index(['Name', 'age', 'Salary', 'Department'], dtype='object')
Name             Amit
age                24
Salary          50000
Department    Finance
Name: 2, dtype: object
<class 'pandas.core.series.Series'>
    Name  age  Salary Department
1  rahul   25   42000         HR
3  priya   23   45000  Marketing
    Name  age  Salary Department
1  rahul   25   42000         HR
2   Amit   24   50000    Finance
3  priya   23   45000  Marketing
Amit
    Name  Salary
0   Riya   35000
1  rahul   42000
2   Amit   50000
3  priya   45000
4   Neha   55000
5   sonu   54000
    Name  Salary
1  rahul   42000
3  priya   45000
Name             Amit
age                24
Salary          50000
Department    Finance
Name: 2, dtype: object
24
   age Department
0   22         AI
1   25         HR
2   24    Finance
3   23  Marketing
4   26         AI
5   27         AI
   age Department
1   25         HR
3   23  Marketing
   age  Salary Department
1   25   42000         HR
2   24   50000    Finance
3   23   45000  Marketing
    Name  age  Salary Department
1  rahul   25   42000         HR
2   Amit   24   50000    Finance
3  priya   23   45000  Marketing
    Name  age  Salary Department
1  rahul   25   42000         HR
2   Amit   24   50000    Finance
3  priya   23   45000  Marketing
4   Neha   26   55000         AI

In [36]:
#boolean indexing
import pandas as pd

data = {
    "ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Riya", "Rahul", "Amit", "Priya", "Neha", "Ankit"],
    "Age": [22, 25, 24, 23, 26, 22],
    "Salary": [35000, 42000, 50000, 45000, 55000, 38000],
    "Department": ["AI", "HR", "Finance", "Marketing", "AI", "AI"]
}
df = pd.DataFrame(data)
print(df.loc[df["Salary"]>40000,["Name"]])
print(df) 
print(df[df["Age"]>23]) 
print(df[df["Salary"]>22])
print(df[df["Department"]=="AI"])
print(df[df["Department"]!="AI"])
print(df[ (df["Department"]=="AI") | (df["Department"]=="HR") ])
print(df[ (df["Department"]=="AI") & (df["Salary"]>36000) ])
print(df[~(df["Department"]=="AI")])

#getting specified column on condition applied not all column
print(df.loc[df["Salary"]>40000,["Name","Salary"]])
print(df[df["Department"].isin(["AI","Finance"])]) 
print(df[df["Age"].between(22,25)])
print(df.query("Age>24"))
print(df.query("Age>25 & Department == 'AI'"))
print(df[df["Salary"]>40000].sort_values("Salary"))

    Name
1  Rahul
2   Amit
3  Priya
4   Neha
    ID   Name  Age  Salary Department
0  101   Riya   22   35000         AI
1  102  Rahul   25   42000         HR
2  103   Amit   24   50000    Finance
3  104  Priya   23   45000  Marketing
4  105   Neha   26   55000         AI
5  106  Ankit   22   38000         AI
    ID   Name  Age  Salary Department
1  102  Rahul   25   42000         HR
2  103   Amit   24   50000    Finance
4  105   Neha   26   55000         AI
    ID   Name  Age  Salary Department
0  101   Riya   22   35000         AI
1  102  Rahul   25   42000         HR
2  103   Amit   24   50000    Finance
3  104  Priya   23   45000  Marketing
4  105   Neha   26   55000         AI
5  106  Ankit   22   38000         AI
    ID   Name  Age  Salary Department
0  101   Riya   22   35000         AI
4  105   Neha   26   55000         AI
5  106  Ankit   22   38000         AI
    ID   Name  Age  Salary Department
1  102  Rahul   25   42000         HR
2  103   Amit   24   50000    Finance
3  104  Priya   23   45000  Marketing
    ID   Name  Age  Salary Department
0  101   Riya   22   35000         AI
1  102  Rahul   25   42000         HR
4  105   Neha   26   55000         AI
5  106  Ankit   22   38000         AI
    ID   Name  Age  Salary Department
4  105   Neha   26   55000         AI
5  106  Ankit   22   38000         AI
    ID   Name  Age  Salary Department
1  102  Rahul   25   42000         HR
2  103   Amit   24   50000    Finance
3  104  Priya   23   45000  Marketing
    Name  Salary
1  Rahul   42000
2   Amit   50000
3  Priya   45000
4   Neha   55000
    ID   Name  Age  Salary Department
0  101   Riya   22   35000         AI
2  103   Amit   24   50000    Finance
4  105   Neha   26   55000         AI
5  106  Ankit   22   38000         AI
    ID   Name  Age  Salary Department
0  101   Riya   22   35000         AI
1  102  Rahul   25   42000         HR
2  103   Amit   24   50000    Finance
3  104  Priya   23   45000  Marketing
5  106  Ankit   22   38000         AI
    ID   Name  Age  Salary Department
1  102  Rahul   25   42000         HR
4  105   Neha   26   55000         AI
    ID  Name  Age  Salary Department
4  105  Neha   26   55000         AI
    ID   Name  Age  Salary Department
1  102  Rahul   25   42000         HR
3  104  Priya   23   45000  Marketing
2  103   Amit   24   50000    Finance
4  105   Neha   26   55000         AI

In [38]:
import pandas as pd

data = {
    "ID": [101, 102, 103, 104],
    "Name": ["Riya", "Rahul", "Amit", "Priya"],
    "Age": [22, 25, 24, 23],
    "Salary": [35000, 42000, 50000, 45000]
}

df = pd.DataFrame(data)

print(df)
df["Department"]=["AI","HR","Finance","Marketing"] #adding new column -them number of values must match the number of rows
print(df)
df["Country"]="India" # scalar quantity
print(df)
df["AnnualSalary"]=df["Salary"]*12
print(df)
df.loc[df["Age"]>23,"Salary"]+=2000 #condition based increment
print(df)
df.rename(
    columns={
        "Name":"EmployeeName",
        "Age":"EmployeeAge"
       },inplace=True
)  #renaming column names
print(df)
# df.index=["A","B","C","D"] 
print(df)
# df=df.drop("Salary",axis=1) #deleting column
# print(df)
# df=df.drop(["AnnualSalary","EmployeeAge"],axis=1)
print(df)
# df=df.drop(3) # delete index row 3
# print(df)
# df=df.drop([1,2])
# print(df)
df.insert(2,"Gender",["F","M","M","F"]) #inserting column at specific position
print(df)
df=df.set_index("ID") #ID become index 
print(df)
df=df.reset_index() #again integers become index
print(df)
df["Department"]=df["Department"].replace( #replace value
  "AI",
  "Artificial intelligence"
)
print(df)
df["Department"] = df["Department"].replace({
    "HR": "Human Resources",
    "Finance": "Accounts"
}) #replace multiple values
print(df)
df["Status"]=df["Salary"].apply(
    lambda x: "High" if x>45000 else "Low"  #creating column based in condition
)
print(df)
df=df[
    ["EmployeeName","ID","Salary","EmployeeAge"]
    ]
print(df)

    ID   Name  Age  Salary
0  101   Riya   22   35000
1  102  Rahul   25   42000
2  103   Amit   24   50000
3  104  Priya   23   45000
    ID   Name  Age  Salary Department
0  101   Riya   22   35000         AI
1  102  Rahul   25   42000         HR
2  103   Amit   24   50000    Finance
3  104  Priya   23   45000  Marketing
    ID   Name  Age  Salary Department Country
0  101   Riya   22   35000         AI   India
1  102  Rahul   25   42000         HR   India
2  103   Amit   24   50000    Finance   India
3  104  Priya   23   45000  Marketing   India
    ID   Name  Age  Salary Department Country  AnnualSalary
0  101   Riya   22   35000         AI   India        420000
1  102  Rahul   25   42000         HR   India        504000
2  103   Amit   24   50000    Finance   India        600000
3  104  Priya   23   45000  Marketing   India        540000
    ID   Name  Age  Salary Department Country  AnnualSalary
0  101   Riya   22   35000         AI   India        420000
1  102  Rahul   25   44000         HR   India        504000
2  103   Amit   24   52000    Finance   India        600000
3  104  Priya   23   45000  Marketing   India        540000
    ID EmployeeName  EmployeeAge  Salary Department Country  AnnualSalary
0  101         Riya           22   35000         AI   India        420000
1  102        Rahul           25   44000         HR   India        504000
2  103         Amit           24   52000    Finance   India        600000
3  104        Priya           23   45000  Marketing   India        540000
    ID EmployeeName  EmployeeAge  Salary Department Country  AnnualSalary
0  101         Riya           22   35000         AI   India        420000
1  102        Rahul           25   44000         HR   India        504000
2  103         Amit           24   52000    Finance   India        600000
3  104        Priya           23   45000  Marketing   India        540000
    ID EmployeeName  EmployeeAge  Salary Department Country  AnnualSalary
0  101         Riya           22   35000         AI   India        420000
1  102        Rahul           25   44000         HR   India        504000
2  103         Amit           24   52000    Finance   India        600000
3  104        Priya           23   45000  Marketing   India        540000
    ID EmployeeName Gender  EmployeeAge  Salary Department Country  \
0  101         Riya      F           22   35000         AI   India
1  102        Rahul      M           25   44000         HR   India
2  103         Amit      M           24   52000    Finance   India
3  104        Priya      F           23   45000  Marketing   India

   AnnualSalary
0        420000
1        504000
2        600000
3        540000
    EmployeeName Gender  EmployeeAge  Salary Department Country  AnnualSalary
ID
101         Riya      F           22   35000         AI   India        420000
102        Rahul      M           25   44000         HR   India        504000
103         Amit      M           24   52000    Finance   India        600000
104        Priya      F           23   45000  Marketing   India        540000
    ID EmployeeName Gender  EmployeeAge  Salary Department Country  \
0  101         Riya      F           22   35000         AI   India
1  102        Rahul      M           25   44000         HR   India
2  103         Amit      M           24   52000    Finance   India
3  104        Priya      F           23   45000  Marketing   India

   AnnualSalary
0        420000
1        504000
2        600000
3        540000
    ID EmployeeName Gender  EmployeeAge  Salary               Department  \
0  101         Riya      F           22   35000  Artificial intelligence
1  102        Rahul      M           25   44000                       HR
2  103         Amit      M           24   52000                  Finance
3  104        Priya      F           23   45000                Marketing

  Country  AnnualSalary
0   India        420000
1   India        504000
2   India        600000
3   India        540000
    ID EmployeeName Gender  EmployeeAge  Salary               Department  \
0  101         Riya      F           22   35000  Artificial intelligence
1  102        Rahul      M           25   44000          Human Resources
2  103         Amit      M           24   52000                 Accounts
3  104        Priya      F           23   45000                Marketing

  Country  AnnualSalary
0   India        420000
1   India        504000
2   India        600000
3   India        540000
    ID EmployeeName Gender  EmployeeAge  Salary               Department  \
0  101         Riya      F           22   35000  Artificial intelligence
1  102        Rahul      M           25   44000          Human Resources
2  103         Amit      M           24   52000                 Accounts
3  104        Priya      F           23   45000                Marketing

  Country  AnnualSalary Status
0   India        420000    Low
1   India        504000    Low
2   India        600000   High
3   India        540000    Low
  EmployeeName   ID  Salary  EmployeeAge
0         Riya  101   35000           22
1        Rahul  102   44000           25
2         Amit  103   52000           24
3        Priya  104   45000           23

In [52]:
import pandas as pd
import numpy as np
data={
    "Name": ["Riya", "Rahul", "Amit", "Priya", "Neha"],
    "Age": [22, np.nan, 24, 23, np.nan],
    "Salary": [35000, 42000, np.nan, 45000, 55000],
    "Department": ["AI", "HR", np.nan, "Marketing", "AI"]
}

df=pd.DataFrame(data)
print(df)
print(type(np.nan))
print(df.isnull())
print(df.isna())
print(df.isnull().sum())#counts total null values in each column
print(df.isnull().sum().sum())#counts total null values ,sums up the total column values count
print(df.notnull())
print(df.dropna()) #remove rows with missing values df.dropna(axis=0)
print(df.dropna(axis=1)) #remove column with missing values
print(df.dropna(how="any")) #remove row if any row has any missing values
print(df.dropna(how="all")) #remove row if whole row has missing value
print(df.dropna(subset=["Age"])) #remove row if age column contain nan value
print(df.dropna(thresh=3))#row must have 3 non null values to be kept

    Name   Age   Salary Department
0   Riya  22.0  35000.0         AI
1  Rahul   NaN  42000.0         HR
2   Amit  24.0      NaN        NaN
3  Priya  23.0  45000.0  Marketing
4   Neha   NaN  55000.0         AI
<class 'float'>
    Name    Age  Salary  Department
0  False  False   False       False
1  False   True   False       False
2  False  False    True        True
3  False  False   False       False
4  False   True   False       False
    Name    Age  Salary  Department
0  False  False   False       False
1  False   True   False       False
2  False  False    True        True
3  False  False   False       False
4  False   True   False       False
Name          0
Age           2
Salary        1
Department    1
dtype: int64
4
   Name    Age  Salary  Department
0  True   True    True        True
1  True  False    True        True
2  True   True   False       False
3  True   True    True        True
4  True  False    True        True
    Name   Age   Salary Department
0   Riya  22.0  35000.0         AI
3  Priya  23.0  45000.0  Marketing
    Name
0   Riya
1  Rahul
2   Amit
3  Priya
4   Neha
    Name   Age   Salary Department
0   Riya  22.0  35000.0         AI
3  Priya  23.0  45000.0  Marketing
    Name   Age   Salary Department
0   Riya  22.0  35000.0         AI
1  Rahul   NaN  42000.0         HR
2   Amit  24.0      NaN        NaN
3  Priya  23.0  45000.0  Marketing
4   Neha   NaN  55000.0         AI
    Name   Age   Salary Department
0   Riya  22.0  35000.0         AI
2   Amit  24.0      NaN        NaN
3  Priya  23.0  45000.0  Marketing
    Name   Age   Salary Department
0   Riya  22.0  35000.0         AI
1  Rahul   NaN  42000.0         HR
3  Priya  23.0  45000.0  Marketing
4   Neha   NaN  55000.0         AI

In [84]:
import pandas as pd
import numpy as np

data = {
    "Name": ["Riya", "Rahul", "Amit", "Priya", "Neha"],
    "Age": [22, np.nan, 24, 23, np.nan],
    "Salary": [35000, 42000, np.nan, 45000, 55000],
    "Department": ["AI", "HR", np.nan, "Marketing", "AI"]
}

df = pd.DataFrame(data)

print(df)
# df=df.fillna("Unknown")  fill nan with unknown
# print(df)
# df=df.fillna(0) fill nan with 0
# print(df)
# df["Age"]=df["Age"].fillna(0)  #fill specific column
# print(df)
# df=df.fillna({  #fill multiple column
#     "Age":0,
#     "Salary":5000,
#     "Department":"Unknown"
# })
# print(df)
# df["Age"]=df["Age"].fillna(df["Age"].mean()) #fill with mean of age
# print(df)
# df["Age"]=df["Age"].fillna(df["Age"].median()) #fill with median of age
# print(df)
# df["Department"]=df["Department"].fillna(df["Department"].mode()[0]) #mode() returns a series ,even if there is only one mode thats why mode()[0]
# print(df)
# df=df.ffill() #fill the previous valid value
# print(df)
# df=df.bfill() #fill the next valid value
# print(df)
# df=df.interpolate() #estimates the missing value by seeing neighbouring value
# print(df)
#filling along column  axis axis=1
# df=df.fillna(method="ffill",axis=1) #fill value fromm previous column within same row
# print(df)

    Name   Age   Salary Department
0   Riya  22.0  35000.0         AI
1  Rahul   NaN  42000.0         HR
2   Amit  24.0      NaN        NaN
3  Priya  23.0  45000.0  Marketing
4   Neha   NaN  55000.0         AI
    Name    Age   Salary Department
0   Riya   22.0  35000.0         AI
1  Rahul  Rahul  42000.0         HR
2   Amit   24.0     24.0       24.0
3  Priya   23.0  45000.0  Marketing
4   Neha   Neha  55000.0         AI

C:\Users\HP\AppData\Local\Temp\ipykernel_25904\3320364854.py:39: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df=df.fillna(method="ffill",axis=1)

In [100]:
import pandas as pd

data = {
    "ID": [101, 102, 103, 104, 105, 106],
    "Name": ["Riya", "Rahul", "Amit", "Priya", "Neha", "Ankit"],
    "Age": [22, 25, 24, 23, 26, 22],
    "Salary": [35000, 42000, 50000, 45000, 55000, 38000],
    "Department": ["AI", "HR", "Finance", "Marketing", "AI", "AI"]
}

df = pd.DataFrame(data)

print(df)
df=df.sort_values(by="Salary") #sort in ascending order
print(df)
df=df.sort_values(by="Salary",ascending=False)
print(df)
df=df.sort_values(by=["Department","Salary"], ascending=[True,False]) #if two employees belomg to same department then it sort by salary
print(df)
df=df.sort_values("Name")
print(df)
df=df.sort_index()
print(df)
print(df.nlargest(3,"Salary")) #top 3 highest salary
print(df.nsmallest(2,"Age")) #smallest 2 age values
df["SalaryRank"]=df["Salary"].rank() #assigns rank from ascending to descending salary
print(df)
df["SalaryRank"]=df["Salary"].rank(ascending=False) #assigns rank from descending salary
print(df)
df["SalaryRank"]=df["Salary"].rank(method="average") #by default 
print(df)
df["SalaryRank"]=df["Salary"].rank(method="dense") 
print(df)

    ID   Name  Age  Salary Department
0  101   Riya   22   35000         AI
1  102  Rahul   25   42000         HR
2  103   Amit   24   50000    Finance
3  104  Priya   23   45000  Marketing
4  105   Neha   26   55000         AI
5  106  Ankit   22   38000         AI
    ID   Name  Age  Salary Department
0  101   Riya   22   35000         AI
5  106  Ankit   22   38000         AI
1  102  Rahul   25   42000         HR
3  104  Priya   23   45000  Marketing
2  103   Amit   24   50000    Finance
4  105   Neha   26   55000         AI
    ID   Name  Age  Salary Department
4  105   Neha   26   55000         AI
2  103   Amit   24   50000    Finance
3  104  Priya   23   45000  Marketing
1  102  Rahul   25   42000         HR
5  106  Ankit   22   38000         AI
0  101   Riya   22   35000         AI
    ID   Name  Age  Salary Department
4  105   Neha   26   55000         AI
5  106  Ankit   22   38000         AI
0  101   Riya   22   35000         AI
2  103   Amit   24   50000    Finance
1  102  Rahul   25   42000         HR
3  104  Priya   23   45000  Marketing
    ID   Name  Age  Salary Department
2  103   Amit   24   50000    Finance
5  106  Ankit   22   38000         AI
4  105   Neha   26   55000         AI
3  104  Priya   23   45000  Marketing
1  102  Rahul   25   42000         HR
0  101   Riya   22   35000         AI
    ID   Name  Age  Salary Department
0  101   Riya   22   35000         AI
1  102  Rahul   25   42000         HR
2  103   Amit   24   50000    Finance
3  104  Priya   23   45000  Marketing
4  105   Neha   26   55000         AI
5  106  Ankit   22   38000         AI
    ID   Name  Age  Salary Department
4  105   Neha   26   55000         AI
2  103   Amit   24   50000    Finance
3  104  Priya   23   45000  Marketing
    ID   Name  Age  Salary Department
0  101   Riya   22   35000         AI
5  106  Ankit   22   38000         AI
    ID   Name  Age  Salary Department  SalaryRank
0  101   Riya   22   35000         AI         1.0
1  102  Rahul   25   42000         HR         3.0
2  103   Amit   24   50000    Finance         5.0
3  104  Priya   23   45000  Marketing         4.0
4  105   Neha   26   55000         AI         6.0
5  106  Ankit   22   38000         AI         2.0
    ID   Name  Age  Salary Department  SalaryRank
0  101   Riya   22   35000         AI         6.0
1  102  Rahul   25   42000         HR         4.0
2  103   Amit   24   50000    Finance         2.0
3  104  Priya   23   45000  Marketing         3.0
4  105   Neha   26   55000         AI         1.0
5  106  Ankit   22   38000         AI         5.0
    ID   Name  Age  Salary Department  SalaryRank
0  101   Riya   22   35000         AI         1.0
1  102  Rahul   25   42000         HR         3.0
2  103   Amit   24   50000    Finance         5.0
3  104  Priya   23   45000  Marketing         4.0
4  105   Neha   26   55000         AI         6.0
5  106  Ankit   22   38000         AI         2.0
    ID   Name  Age  Salary Department  SalaryRank
0  101   Riya   22   35000         AI         1.0
1  102  Rahul   25   42000         HR         3.0
2  103   Amit   24   50000    Finance         5.0
3  104  Priya   23   45000  Marketing         4.0
4  105   Neha   26   55000         AI         6.0
5  106  Ankit   22   38000         AI         2.0

In [114]:
#groupby-used to split the data into groups,apply one or more operations to each group,combine the result
import pandas as pd

data = {
    "Name": ["Riya", "Rahul", "Amit", "Priya", "Neha", "Ankit"],
    "Department": ["AI", "HR", "Finance", "Marketing", "AI", "AI"],
    "Age": [22, 25, 24, 23, 26, 22],
    "Salary": [35000, 42000, 50000, 45000, 55000, 38000]
}

df = pd.DataFrame(data)

print(df)
df.groupby("Department")["Salary"].mean()
df.groupby("Department")["Salary"].sum()
df.groupby("Department")["Salary"].count() #count non null value row
df.groupby("Department")["Salary"].size() #count all rows even null values row
df.groupby("Department")["Salary"].min() #show min salary in each department
df.groupby("Department")["Salary"].max() #highest salary  in each department
df.groupby("Department")["Salary"].median() 
df.groupby("Department")["Salary"].std() #for department with only one employee the result is nan
df.groupby("Department")["Salary"].agg(["sum","mean","min","max","count"])
df.groupby("Department").agg(AverageSalary=("Salary","mean"),HighestSalary=("Salary","max"),TotalEmployees=("Name","count"))
df["Gender"]=["F","M","M","F","F","M"]
df.groupby(["Department","Gender"])["Salary"].mean() #group by multiple columns
#by default grouped columns become index,to keep it normal
df.groupby("Department",as_index=False)["Salary"].mean()

    Name Department  Age  Salary
0   Riya         AI   22   35000
1  Rahul         HR   25   42000
2   Amit    Finance   24   50000
3  Priya  Marketing   23   45000
4   Neha         AI   26   55000
5  Ankit         AI   22   38000

  Department        Salary
0         AI  42666.666667
1    Finance  50000.000000
2         HR  42000.000000
3  Marketing  45000.000000

In [132]:
import pandas as pd

data = {
    "Name": ["Riya", "Rahul", "Amit", "Priya", "Neha", "Ankit"],
    "Department": ["AI", "HR", "Finance", "Marketing", "AI", "AI"],
    "Salary": [35000, 42000, 50000, 45000, 55000, 38000]
}

df = pd.DataFrame(data)

print(df)
# df["DeptAvgSalary"]=(df.groupby("Department")["Salary"].transform("mean")) #returns same number of row and adds a column
# print(df)
# df["Difference"]=df["Salary"] - df.groupby("Department")["Salary"].transform("mean")
# print(df)
print("")
# df=df.groupby("Department")["Salary"].filter(lambda x: len(x)>0).mean() #keep department having more than one employee
print(df)
df.groupby("Department").filter( lambda x: x["Salary"].mean() > 43000)
#apply - most flexible method- allows custom functions
df["DoubleSalary"]=df["Salary"].apply( lambda x: x*2 )
print(df)
df["Name"]=df["Name"].apply(
    lambda x: x.upper()
)
print(df)
df.groupby("Department")["Salary"].apply(
    lambda x: x.max()-x.min()
)

    Name Department  Salary
0   Riya         AI   35000
1  Rahul         HR   42000
2   Amit    Finance   50000
3  Priya  Marketing   45000
4   Neha         AI   55000
5  Ankit         AI   38000

    Name Department  Salary
0   Riya         AI   35000
1  Rahul         HR   42000
2   Amit    Finance   50000
3  Priya  Marketing   45000
4   Neha         AI   55000
5  Ankit         AI   38000
    Name Department  Salary  DoubleSalary
0   Riya         AI   35000         70000
1  Rahul         HR   42000         84000
2   Amit    Finance   50000        100000
3  Priya  Marketing   45000         90000
4   Neha         AI   55000        110000
5  Ankit         AI   38000         76000
    Name Department  Salary  DoubleSalary
0   RIYA         AI   35000         70000
1  RAHUL         HR   42000         84000
2   AMIT    Finance   50000        100000
3  PRIYA  Marketing   45000         90000
4   NEHA         AI   55000        110000
5  ANKIT         AI   38000         76000

Department
AI           20000
Finance          0
HR               0
Marketing        0
Name: Salary, dtype: int64

In [2]:
import pandas as pd

df1 = pd.DataFrame({
    "Name": ["Riya", "Rahul"],
    "Age": [22, 23]
})

# print(df1)

df2 = pd.DataFrame({
    "Name": ["Amit", "Neha"],
    "Age": [24, 25]
})

# print(df2)
# pd.concat([df1, df2],ignore_index=True) #vertical concatenation
# pd.concat([df1,df2],axis=1) #horizontal concat
df3 = pd.DataFrame({
    "Name": ["Riya", "Rahul", "Amit"]
})

df4 = pd.DataFrame({
    "Salary": [35000, 42000]
})
pd.concat([df3, df4], axis=0) #when row count differ pandas fill with nan
# pd.concat([df1,df2],keys=["Students","Teachers"]) #multiindex keep track each row where it from
# pd.concat(
#     [df1,df2],
#     verify_integrity=True
# ) #give error if duplicate indexes foound instead of allowing duplicates

    Name   Salary
0   Riya      NaN
1  Rahul      NaN
2   Amit      NaN
0    NaN  35000.0
1    NaN  42000.0

In [169]:
employees = pd.DataFrame({
    "EmployeeID": [101, 102, 103, 104],
    "Name": ["Riya", "Rahul", "Amit", "Neha"],
    "DepartmentID": [1, 2, 3, 1]
})

departments = pd.DataFrame({
    "DepartmentID": [1, 2, 3],
    "Department": ["AI", "HR", "Finance"],
    "Name":["A","B","C"]
})

# pd.merge(
#     employees,
#     departments,
#     on="DepartmentID"
# )

# pd.merge(
#     employees,
#     departments,
#     on="DepartmentID",
#     how="inner"
# ) #default return matching rows

# pd.merge(
#     employees,
#     departments,
#     on="DepartmentID",
#     how="left"
# ) #keep all rows from left dataframe
# pd.merge(
#     employees,
#     departments,
#     on="DepartmentID",
#     how="right"
# ) #keep all rows from right dataframe

# pd.merge(
#     employees,
#     departments,
#     on="DepartmentID",
#     how="outer"
# ) #keep all rows from both dataframe 

pd.merge(
    employees,
    departments,
    on="DepartmentID",
    suffixes=("_Employee","_Manager"),
    how="inner"
    
)

   EmployeeID Name_Employee  DepartmentID Department Name_Manager
0         101          Riya             1         AI            A
1         102         Rahul             2         HR            B
2         103          Amit             3    Finance            C
3         104          Neha             1         AI            A

In [184]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "ID": [101, 102, 103, 104, 105, 105],
    "Name": ["Riya", "Rahul", "Amit", "Priya", "Neha", "Neha"],
    "Gender": ["F", "M", "M", "other", "F", "F"],
    "Department": ["AI", "HR", "Finance", "Marketing", "AI", "AI"],
    "Salary": [35000, 42000, 50000, 45000, 55000, 55000],
    "Age": [22, 25, 24, 23, 26, 26]
})

# print(df)
# df["Department"] = df["Department"].replace("AI", "Artificial Intelligence")
# df["Gender"]=df["Gender"].map({
#     "M":"Male",
#     "F":"Female"
# }) #map converts value not found in dictionary  to nan ,replace print as it is
# print(df)

df["Age"]=df["Age"].astype(float)
print(df)

df.rename(columns={
    "Salary":"MonthlySalary"
})
# df.duplicated()
df.duplicated(subset="ID") #return true to duplicate row and other as false
df.drop_duplicates()
df["Department"].unique() #return unique values
df["Department"].nunique() #return number if unique values
df["Department"].value_counts() #count ocurences of each value
df["Department"].value_counts(normalize=True)

    ID   Name Gender Department  Salary   Age
0  101   Riya      F         AI   35000  22.0
1  102  Rahul      M         HR   42000  25.0
2  103   Amit      M    Finance   50000  24.0
3  104  Priya  other  Marketing   45000  23.0
4  105   Neha      F         AI   55000  26.0
5  105   Neha      F         AI   55000  26.0

Department
AI           0.500000
HR           0.166667
Finance      0.166667
Marketing    0.166667
Name: proportion, dtype: float64

In [217]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Riya", "Rahul", "Amit", "Neha"],
    "JoiningDate": [
        "2024-01-10",
        "2023-08-15",
        "2024-05-20",
        "2025-02-01"
    ],
    "Salary": [35000, 42000, 50000, 55000]
})

print(df)
print(df.dtypes)
df["JoiningDate"]=pd.to_datetime(df["JoiningDate"])
# print(df.dtypes)
# pd.to_datetime("2025-07-01") # all produce same datetime object
# pd.to_datetime("01/07/2025")
# pd.to_datetime("July 1,2025")
# pd.to_datetime("1 July 2025")
df["joiningDate"]=pd.to_datetime(
    df["JoiningDate"],
    format="%Y-%m-%d"
)
# pd.Timestamp.now() #current timestamp
# pd.Timestamp.today().date() #todays date
df["year"]=df["JoiningDate"].dt.year
print(df["year"])
df["month"]=df["joiningDate"].dt.month
print(df["month"])
df["Day"]=df["joiningDate"].dt.day
print(df["Day"])
df["Hour"] = df["JoiningDate"].dt.hour
print(df["Hour"])
df["MonthName"]=df["JoiningDate"].dt.month_name()
print(df["MonthName"])
df["DayName"]=df["JoiningDate"].dt.day_name()
print(df["DayName"])
# df["JoiningDate"].dt.dayofweek
df["Weekend"]=df["JoiningDate"].dt.dayofweek 
print(df["Weekend"])
df["JoiningDate"]+pd.Timedelta(days=10) #add 10days to date
df["JoiningDate"]-pd.Timedelta(days=30) #subtract 1 month
pd.Timedelta(days=5) #represent days
pd.Timedelta(hours=12)
pd.Timedelta(minutes=90)
#difference between dates
today=pd.Timestamp.today()
df["Experience"]=today-df["JoiningDate"]
print(df["Experience"])
df.sort_values("JoiningDate",ascending=False) 
#filter_values
df[df["JoiningDate"]>"2024-01-01"]
df[df["JoiningDate"].dt.year==2024]
pd.date_range(
    start="2025-01-01",
    periods=5
) #create date in range 5  automatically

pd.date_range(
    start="2025-01-01",
    periods=6,
    freq="M"
) #create date in range 6 changing month

    Name JoiningDate  Salary
0   Riya  2024-01-10   35000
1  Rahul  2023-08-15   42000
2   Amit  2024-05-20   50000
3   Neha  2025-02-01   55000
Name           object
JoiningDate    object
Salary          int64
dtype: object
0    2024
1    2023
2    2024
3    2025
Name: year, dtype: int32
0    1
1    8
2    5
3    2
Name: month, dtype: int32
0    10
1    15
2    20
3     1
Name: Day, dtype: int32
0    0
1    0
2    0
3    0
Name: Hour, dtype: int32
0     January
1      August
2         May
3    February
Name: MonthName, dtype: object
0    Wednesday
1      Tuesday
2       Monday
3     Saturday
Name: DayName, dtype: object
0    2
1    1
2    0
3    5
Name: Weekend, dtype: int32
0    903 days 18:10:16.760834
1   1051 days 18:10:16.760834
2    772 days 18:10:16.760834
3    515 days 18:10:16.760834
Name: Experience, dtype: timedelta64[ns]

DatetimeIndex(['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04',
               '2025-01-05'],
              dtype='datetime64[ns]', freq='D')

In [240]:
import pandas as pd

df = pd.DataFrame({
    "Department": ["AI", "AI", "HR", "Finance", "HR"],
    "Name": ["Riya", "Neha", "Rahul", "Amit", "Ankit"],
    "Salary": [35000, 55000, 42000, 50000, 38000],
    "Age": [22, 26, 25, 24, 23]
})

print(df)
# df1=df.set_index("Department")
# print(df1)
# df1.loc["AI"]
df1=df.set_index(["Department","Name"])
print(df1)
df1.loc[("AI","Neha")]
df1.loc[[("AI","Riya"),("HR","Rahul")]]
# df1=df1.reset_index()
# print(df1)
df1=df1.sort_index()
print(df1)
df1.loc["AI"]
df1.loc[("HR","Rahul")]
df1.swaplevel()
df1.droplevel("Department")
df1.index.get_level_values("Department")

  Department   Name  Salary  Age
0         AI   Riya   35000   22
1         AI   Neha   55000   26
2         HR  Rahul   42000   25
3    Finance   Amit   50000   24
4         HR  Ankit   38000   23
                  Salary  Age
Department Name
AI         Riya    35000   22
           Neha    55000   26
HR         Rahul   42000   25
Finance    Amit    50000   24
HR         Ankit   38000   23
                  Salary  Age
Department Name
AI         Neha    55000   26
           Riya    35000   22
Finance    Amit    50000   24
HR         Ankit   38000   23
           Rahul   42000   25

Index(['AI', 'AI', 'Finance', 'HR', 'HR'], dtype='object', name='Department')

In [261]:
import pandas as pd

df = pd.DataFrame({
    "Employee": ["Riya","Rahul","Riya","Neha","Rahul","Amit","Neha","Amit"],
    "Department": ["AI","HR","AI","AI","HR","Finance","AI","Finance"],
    "Product": ["Laptop","Mouse","Keyboard","Laptop","Laptop","Mouse","Keyboard","Laptop"],
    "Sales": [50000,1000,2000,55000,45000,1200,2500,60000]
})

print(df)
pd.pivot_table(
    df,
    values="Sales",
    index="Department",
    aggfunc="sum"
)
pd.pivot_table(
    df,
    values="Sales",
    index=["Department","Employee"],
    aggfunc="sum"
)
pd.pivot_table(
    df,
    values="Sales",
    index="Department",
    aggfunc=["sum","mean","max"],
    fill_value=0
)
pd.pivot_table(
    df,
    values="Sales",
    index="Department",
    columns="Product",
    aggfunc="sum",
    fill_value=0
)
df["Quantity"]=[5,1,1,6,4,2,2,5]
pd.pivot_table(
    df,
    values=["Sales","Quantity"],
    index="Department",
    aggfunc="sum"
)
pd.pivot_table(
    df,
    values="Sales",
    index="Department",
    aggfunc="sum",
    margins=True #grand total
)

pivot=pd.pivot_table(
    df,
    values="Sales",
    index="Department",
    aggfunc="sum",
)
pivot[pivot["Sales"]>46000]
df.groupby("Department")["Sales"].sum() #pivot vs group by
#pivot used only when there are no duplicate combinations of index and columns-if an employee has two sales of same product

  Employee Department   Product  Sales
0     Riya         AI    Laptop  50000
1    Rahul         HR     Mouse   1000
2     Riya         AI  Keyboard   2000
3     Neha         AI    Laptop  55000
4    Rahul         HR    Laptop  45000
5     Amit    Finance     Mouse   1200
6     Neha         AI  Keyboard   2500
7     Amit    Finance    Laptop  60000

Department
AI         109500
Finance     61200
HR          46000
Name: Sales, dtype: int64

In [14]:
import pandas as pd

df = pd.DataFrame({
    "Student": ["Riya", "Rahul", "Amit"],
    "Math": [90, 78, 85],
    "Science": [85, 92, 80],
    "English": [88, 81, 89]
})

print(df)
pd.melt(df) #everything become 2 column
pd.melt(df,
        id_vars="Student") #student become fixed other are converted into column
pd.melt(df,
        id_vars="Student",
        var_name="Subject",
        value_name="Marks"
       )
df=df.set_index("Student")
stacked=df.stack() #convert column into index (Math science become another level of index)
print(stacked)
stacked.unstack() #index to columns

  Student  Math  Science  English
0    Riya    90       85       88
1   Rahul    78       92       81
2    Amit    85       80       89
Student
Riya     Math       90
         Science    85
         English    88
Rahul    Math       78
         Science    92
         English    81
Amit     Math       85
         Science    80
         English    89
dtype: int64

         Math  Science  English
Student
Riya       90       85       88
Rahul      78       92       81
Amit       85       80       89

In [16]:
df = pd.DataFrame({
    "Name":["Riya","Rahul"],
    "Skills":[
        ["Python","SQL","Pandas"],
        ["Java","C++"] 
    ]  #column contains list
})  

print(df)
df.explode("Skills") #each list item become its own row

    Name                 Skills
0   Riya  [Python, SQL, Pandas]
1  Rahul            [Java, C++]

    Name  Skills
0   Riya  Python
0   Riya     SQL
0   Riya  Pandas
1  Rahul    Java
1  Rahul     C++

In [17]:
df = pd.DataFrame({
    "Student":["Riya","Rahul"],
    "Math_2023":[90,80],
    "Math_2024":[95,85]
})

print(df)
pd.wide_to_long(df,
                stubnames="Math",
                i="Student",
                j="Year",
                sep="_"
               )

  Student  Math_2023  Math_2024
0    Riya         90         95
1   Rahul         80         85

              Math
Student Year
Riya    2023    90
Rahul   2023    80
Riya    2024    95
Rahul   2024    85

In [20]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Riya","Rahul","Amit","Neha","Ankit","Priya"],
    "Gender": ["F","M","M","F","M","F"],
    "Department": ["AI","HR","Finance","AI","HR","Finance"],
    "Result": ["Pass","Pass","Fail","Pass","Fail","Pass"]
})

print(df)
pd.crosstab(
    df["Gender"],
    df["Department"],
    margins="True" , #gives total and grand total
    margins_name="Total"
) #A crosstab counts the frequency of combinations between two categorial column

pd.crosstab(
    df["Gender"],
    df["Department"],
    normalize=True
) #gives percentage instead of counts

    Name Gender Department Result
0   Riya      F         AI   Pass
1  Rahul      M         HR   Pass
2   Amit      M    Finance   Fail
3   Neha      F         AI   Pass
4  Ankit      M         HR   Fail
5  Priya      F    Finance   Pass

Department        AI   Finance        HR
Gender
F           0.333333  0.166667  0.000000
M           0.000000  0.166667  0.333333

In [23]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Riya","Rahul","Amit","Neha","Ankit","Priya"],
    "Gender": ["F","M","M","F","M","F"],
    "Department": ["AI","HR","Finance","AI","HR","Finance"],
    "Result": ["Pass","Pass","Fail","Pass","Fail","Pass"]
})

print(df)
encoded=pd.get_dummies(df["Department"],prefix="Dept",drop_first=True,dtype=int)
df=pd.concat([df,encoded],axis=1)
print(df)

    Name Gender Department Result
0   Riya      F         AI   Pass
1  Rahul      M         HR   Pass
2   Amit      M    Finance   Fail
3   Neha      F         AI   Pass
4  Ankit      M         HR   Fail
5  Priya      F    Finance   Pass
    Name Gender Department Result  Dept_Finance  Dept_HR
0   Riya      F         AI   Pass             0        0
1  Rahul      M         HR   Pass             0        1
2   Amit      M    Finance   Fail             1        0
3   Neha      F         AI   Pass             0        0
4  Ankit      M         HR   Fail             0        1
5  Priya      F    Finance   Pass             1        0

In [34]:
import pandas as pd

sales = pd.DataFrame({
    "Day":[1,2,3,4,5,6,7],
    "Sales":[100,120,150,180,170,200,220]
})

print(sales) 
sales["Sales"].rolling(3,min_periods=1).mean()#looks at fixed number of previous rows 
sales["Sales"].rolling(3,min_periods=1).sum()
sales["Sales"].rolling(3,min_periods=1).min()
sales["Sales"].expanding().sum()

   Day  Sales
0    1    100
1    2    120
2    3    150
3    4    180
4    5    170
5    6    200
6    7    220

In [3]:
import pandas as pd

df = pd.DataFrame({
    "A":[10,20,30]
})

print(type(df["A"]))

<class 'pandas.core.series.Series'>

In [4]:
import pandas as pd

df = pd.DataFrame({
    "A":[10,20],
    "B":[30,40]
})

print(type(df[["A"]]))

<class 'pandas.core.frame.DataFrame'>

In [5]:
import pandas as pd

s = pd.Series([10,20,30], index=["A","B","C"])

print(s["B"])

20

In [9]:
df = pd.DataFrame({
    "Salary":[50000,60000,70000]
})
df["ranking"]=df["Salary"].rank(ascending=False)
print(df)

   Salary  ranking
0   50000      3.0
1   60000      2.0
2   70000      1.0