In [2]:
import pandas as pd
import numpy as np

In [133]:

df = pd.DataFrame({
    "EmpID":[101,102,103,104,105,106,107,108,109,110],
    "Name":["Riya","Rahul","Neha","Amit","Priya","Karan","Anjali","Rohit","Sneha","Arjun"],
    "Department":["AI","HR","Finance","AI","HR","Finance","AI","HR","Finance","AI"],
    "Gender":["F","M","F","M","F","M","F","M","F","M"],
    "Age":[23,30,28,35,26,40,29,31,27,33],
    "Salary":[45000,52000,60000,70000,48000,65000,55000,51000,62000,72000],
    "Experience":[1,5,4,8,2,10,5,6,3,9],
    "City":["Indore","Bhopal","Indore","Delhi","Delhi","Mumbai","Indore","Mumbai","Delhi","Bhopal"],
    "JoiningDate":pd.to_datetime([
        "2023-01-10","2020-05-15","2021-03-20","2018-07-11",
        "2022-06-18","2016-09-25","2020-11-05","2019-04-17",
        "2021-12-01","2017-08-09"
    ])
})
print(df)
print(df.iloc[0,2])

   EmpID    Name Department Gender  Age  Salary  Experience    City  \
0    101    Riya         AI      F   23   45000           1  Indore
1    102   Rahul         HR      M   30   52000           5  Bhopal
2    103    Neha    Finance      F   28   60000           4  Indore
3    104    Amit         AI      M   35   70000           8   Delhi
4    105   Priya         HR      F   26   48000           2   Delhi
5    106   Karan    Finance      M   40   65000          10  Mumbai
6    107  Anjali         AI      F   29   55000           5  Indore
7    108   Rohit         HR      M   31   51000           6  Mumbai
8    109   Sneha    Finance      F   27   62000           3   Delhi
9    110   Arjun         AI      M   33   72000           9  Bhopal

  JoiningDate
0  2023-01-10
1  2020-05-15
2  2021-03-20
3  2018-07-11
4  2022-06-18
5  2016-09-25
6  2020-11-05
7  2019-04-17
8  2021-12-01
9  2017-08-09
AI

In [128]:
print(df)
print(df.iloc[0,1])

<pandas.core.groupby.generic.DataFrameGroupBy object at 0x0000028684623050>

AttributeError: 'DataFrameGroupBy' object has no attribute 'iloc'

In [11]:
df.head(5)

   EmpID   Name Department Gender  Age  Salary  Experience    City JoiningDate
0    101   Riya         AI      F   23   45000           1  Indore  2023-01-10
1    102  Rahul         HR      M   30   52000           5  Bhopal  2020-05-15
2    103   Neha    Finance      F   28   60000           4  Indore  2021-03-20
3    104   Amit         AI      M   35   70000           8   Delhi  2018-07-11
4    105  Priya         HR      F   26   48000           2   Delhi  2022-06-18

In [12]:
df.tail(3)

   EmpID   Name Department Gender  Age  Salary  Experience    City JoiningDate
7    108  Rohit         HR      M   31   51000           6  Mumbai  2019-04-17
8    109  Sneha    Finance      F   27   62000           3   Delhi  2021-12-01
9    110  Arjun         AI      M   33   72000           9  Bhopal  2017-08-09

In [13]:
print(df.shape)

(10, 9)

In [14]:
print(df.columns)

Index(['EmpID', 'Name', 'Department', 'Gender', 'Age', 'Salary', 'Experience',
       'City', 'JoiningDate'],
      dtype='object')

In [20]:
# print(df.dtypes)
# print(df.index)
print(df.describe)

<bound method NDFrame.describe of    EmpID    Name Department Gender  Age  Salary  Experience    City  \
0    101    Riya         AI      F   23   45000           1  Indore
1    102   Rahul         HR      M   30   52000           5  Bhopal
2    103    Neha    Finance      F   28   60000           4  Indore
3    104    Amit         AI      M   35   70000           8   Delhi
4    105   Priya         HR      F   26   48000           2   Delhi
5    106   Karan    Finance      M   40   65000          10  Mumbai
6    107  Anjali         AI      F   29   55000           5  Indore
7    108   Rohit         HR      M   31   51000           6  Mumbai
8    109   Sneha    Finance      F   27   62000           3   Delhi
9    110   Arjun         AI      M   33   72000           9  Bhopal

  JoiningDate
0  2023-01-10
1  2020-05-15
2  2021-03-20
3  2018-07-11
4  2022-06-18
5  2016-09-25
6  2020-11-05
7  2019-04-17
8  2021-12-01
9  2017-08-09  >

In [26]:
print(df[["Name","Salary"]])

     Name  Salary
0    Riya   45000
1   Rahul   52000
2    Neha   60000
3    Amit   70000
4   Priya   48000
5   Karan   65000
6  Anjali   55000
7   Rohit   51000
8   Sneha   62000
9   Arjun   72000

In [27]:
print(df.loc[2:7])

   EmpID    Name Department Gender  Age  Salary  Experience    City  \
2    103    Neha    Finance      F   28   60000           4  Indore
3    104    Amit         AI      M   35   70000           8   Delhi
4    105   Priya         HR      F   26   48000           2   Delhi
5    106   Karan    Finance      M   40   65000          10  Mumbai
6    107  Anjali         AI      F   29   55000           5  Indore
7    108   Rohit         HR      M   31   51000           6  Mumbai

  JoiningDate
2  2021-03-20
3  2018-07-11
4  2022-06-18
5  2016-09-25
6  2020-11-05
7  2019-04-17

In [60]:
print(df[df["Salary"]>60000])

   EmpID   Name Department Gender  Age  Salary  Experience    City JoiningDate
3    104   Amit         AI      M   35   70000           8   Delhi  2018-07-11
5    106  Karan    Finance      M   40   65000          10  Mumbai  2016-09-25
8    109  Sneha    Finance      F   27   62000           3   Delhi  2021-12-01
9    110  Arjun         AI      M   33   72000           9  Bhopal  2017-08-09

In [38]:
print(df.query("Age >= 25 and Age <= 35"))

   EmpID    Name Department Gender  Age  Salary  Experience    City  \
1    102   Rahul         HR      M   30   52000           5  Bhopal
2    103    Neha    Finance      F   28   60000           4  Indore
3    104    Amit         AI      M   35   70000           8   Delhi
4    105   Priya         HR      F   26   48000           2   Delhi
6    107  Anjali         AI      F   29   55000           5  Indore
7    108   Rohit         HR      M   31   51000           6  Mumbai
8    109   Sneha    Finance      F   27   62000           3   Delhi
9    110   Arjun         AI      M   33   72000           9  Bhopal

  JoiningDate
1  2020-05-15
2  2021-03-20
3  2018-07-11
4  2022-06-18
6  2020-11-05
7  2019-04-17
8  2021-12-01
9  2017-08-09

In [42]:
print(df.loc[:,["Name","Salary","Department"]])

     Name  Salary Department
0    Riya   45000         AI
1   Rahul   52000         HR
2    Neha   60000    Finance
3    Amit   70000         AI
4   Priya   48000         HR
5   Karan   65000    Finance
6  Anjali   55000         AI
7   Rohit   51000         HR
8   Sneha   62000    Finance
9   Arjun   72000         AI

In [44]:
print(df.query("Department == 'AI' and Salary >50000"))

   EmpID    Name Department Gender  Age  Salary  Experience    City  \
3    104    Amit         AI      M   35   70000           8   Delhi
6    107  Anjali         AI      F   29   55000           5  Indore
9    110   Arjun         AI      M   33   72000           9  Bhopal

  JoiningDate
3  2018-07-11
6  2020-11-05
9  2017-08-09

In [45]:
print(df.query("Department == 'HR' or Department == 'Finance'"))

   EmpID   Name Department Gender  Age  Salary  Experience    City JoiningDate
1    102  Rahul         HR      M   30   52000           5  Bhopal  2020-05-15
2    103   Neha    Finance      F   28   60000           4  Indore  2021-03-20
4    105  Priya         HR      F   26   48000           2   Delhi  2022-06-18
5    106  Karan    Finance      M   40   65000          10  Mumbai  2016-09-25
7    108  Rohit         HR      M   31   51000           6  Mumbai  2019-04-17
8    109  Sneha    Finance      F   27   62000           3   Delhi  2021-12-01

In [47]:
print(df[df["Department"]!="AI"])

   EmpID   Name Department Gender  Age  Salary  Experience    City JoiningDate
1    102  Rahul         HR      M   30   52000           5  Bhopal  2020-05-15
2    103   Neha    Finance      F   28   60000           4  Indore  2021-03-20
4    105  Priya         HR      F   26   48000           2   Delhi  2022-06-18
5    106  Karan    Finance      M   40   65000          10  Mumbai  2016-09-25
7    108  Rohit         HR      M   31   51000           6  Mumbai  2019-04-17
8    109  Sneha    Finance      F   27   62000           3   Delhi  2021-12-01

In [51]:
print(df[(df["City"]=="Delhi") & (df["Salary"]>5000)])

   EmpID   Name Department Gender  Age  Salary  Experience   City JoiningDate
3    104   Amit         AI      M   35   70000           8  Delhi  2018-07-11
4    105  Priya         HR      F   26   48000           2  Delhi  2022-06-18
8    109  Sneha    Finance      F   27   62000           3  Delhi  2021-12-01

In [56]:
print(df[df["Experience"].isin([2,5,8])])

   EmpID    Name Department Gender  Age  Salary  Experience    City  \
1    102   Rahul         HR      M   30   52000           5  Bhopal
3    104    Amit         AI      M   35   70000           8   Delhi
4    105   Priya         HR      F   26   48000           2   Delhi
6    107  Anjali         AI      F   29   55000           5  Indore

  JoiningDate
1  2020-05-15
3  2018-07-11
4  2022-06-18
6  2020-11-05

In [61]:
print(df.loc[df["Salary"]>40000,["Name","Salary"]])

     Name  Salary
0    Riya   45000
1   Rahul   52000
2    Neha   60000
3    Amit   70000
4   Priya   48000
5   Karan   65000
6  Anjali   55000
7   Rohit   51000
8   Sneha   62000
9   Arjun   72000

In [66]:
print(df.loc[((df["Department"]=="AI") | (df["Department"]=="HR")) & (df["Age"]<30)])
print(df.iloc[

   EmpID    Name Department Gender  Age  Salary  Experience    City  \
0    101    Riya         AI      F   23   45000           1  Indore
4    105   Priya         HR      F   26   48000           2   Delhi
6    107  Anjali         AI      F   29   55000           5  Indore

  JoiningDate
0  2023-01-10
4  2022-06-18
6  2020-11-05

In [111]:
print(df.loc[df["Salary"]>7000,["Name","Age"]])

     Name  Age
0    Riya   23
1   Rahul   30
2    Neha   28
3    Amit   35
4   Priya   26
5   Karan   40
6  Anjali   29
7   Rohit   31
8   Sneha   27
9   Arjun   33

In [71]:
print(df.query("Salary > 50000 & Age <30"))

   EmpID    Name Department Gender  Age  Salary  Experience    City  \
2    103    Neha    Finance      F   28   60000           4  Indore
6    107  Anjali         AI      F   29   55000           5  Indore
8    109   Sneha    Finance      F   27   62000           3   Delhi

  JoiningDate
2  2021-03-20
6  2020-11-05
8  2021-12-01

In [75]:
print(df.sort_values("Salary"))

   EmpID    Name Department Gender  Age  Salary  Experience    City  \
0    101    Riya         AI      F   23   45000           1  Indore
4    105   Priya         HR      F   26   48000           2   Delhi
7    108   Rohit         HR      M   31   51000           6  Mumbai
1    102   Rahul         HR      M   30   52000           5  Bhopal
6    107  Anjali         AI      F   29   55000           5  Indore
2    103    Neha    Finance      F   28   60000           4  Indore
8    109   Sneha    Finance      F   27   62000           3   Delhi
5    106   Karan    Finance      M   40   65000          10  Mumbai
3    104    Amit         AI      M   35   70000           8   Delhi
9    110   Arjun         AI      M   33   72000           9  Bhopal

  JoiningDate
0  2023-01-10
4  2022-06-18
7  2019-04-17
1  2020-05-15
6  2020-11-05
2  2021-03-20
8  2021-12-01
5  2016-09-25
3  2018-07-11
9  2017-08-09

In [78]:
print(df.sort_values(by=["Department","Salary"],ascending=[True,False]))

   EmpID    Name Department Gender  Age  Salary  Experience    City  \
9    110   Arjun         AI      M   33   72000           9  Bhopal
3    104    Amit         AI      M   35   70000           8   Delhi
6    107  Anjali         AI      F   29   55000           5  Indore
0    101    Riya         AI      F   23   45000           1  Indore
5    106   Karan    Finance      M   40   65000          10  Mumbai
8    109   Sneha    Finance      F   27   62000           3   Delhi
2    103    Neha    Finance      F   28   60000           4  Indore
1    102   Rahul         HR      M   30   52000           5  Bhopal
7    108   Rohit         HR      M   31   51000           6  Mumbai
4    105   Priya         HR      F   26   48000           2   Delhi

  JoiningDate
9  2017-08-09
3  2018-07-11
6  2020-11-05
0  2023-01-10
5  2016-09-25
8  2021-12-01
2  2021-03-20
1  2020-05-15
7  2019-04-17
4  2022-06-18

In [81]:
df["rank"]=df["Salary"].rank()
print(df)

   EmpID    Name Department Gender  Age  Salary  Experience    City  \
0    101    Riya         AI      F   23   45000           1  Indore
1    102   Rahul         HR      M   30   52000           5  Bhopal
2    103    Neha    Finance      F   28   60000           4  Indore
3    104    Amit         AI      M   35   70000           8   Delhi
4    105   Priya         HR      F   26   48000           2   Delhi
5    106   Karan    Finance      M   40   65000          10  Mumbai
6    107  Anjali         AI      F   29   55000           5  Indore
7    108   Rohit         HR      M   31   51000           6  Mumbai
8    109   Sneha    Finance      F   27   62000           3   Delhi
9    110   Arjun         AI      M   33   72000           9  Bhopal

  JoiningDate  rank
0  2023-01-10   1.0
1  2020-05-15   4.0
2  2021-03-20   6.0
3  2018-07-11   9.0
4  2022-06-18   2.0
5  2016-09-25   8.0
6  2020-11-05   5.0
7  2019-04-17   3.0
8  2021-12-01   7.0
9  2017-08-09  10.0

In [87]:
top3=df.nlargest(3,"Salary")[["Name","Salary"]]
print(top3)

    Name  Salary
9  Arjun   72000
3   Amit   70000
5  Karan   65000

In [88]:
bottom2=df.nsmallest(2,"Salary")[["Name","Salary"]]
print(bottom2)

    Name  Salary
0   Riya   45000
4  Priya   48000

In [92]:
df.groupby("Department")["Salary"].mean()

Department
AI         60500.000000
Finance    62333.333333
HR         50333.333333
Name: Salary, dtype: float64

In [94]:
df.groupby("City")["Salary"].max()

City
Bhopal    72000
Delhi     70000
Indore    60000
Mumbai    65000
Name: Salary, dtype: int64

In [95]:
df.groupby("Department")["Name"].count()

Department
AI         4
Finance    3
HR         3
Name: Name, dtype: int64

In [96]:
df.groupby("Department")["Salary"].sum()

Department
AI         242000
Finance    187000
HR         151000
Name: Salary, dtype: int64

In [97]:
df["Salary"].agg(["mean","max","min"])

mean    58000.0
max     72000.0
min     45000.0
Name: Salary, dtype: float64

In [106]:
print(df.groupby("Department")["Salary"].mean().idxmax()) #department which avg salary is highest

62333.333333333336

In [108]:
print(df.groupby("Department")["Salary"].apply(lambda x: x.max()- x.min()))

Department
AI         27000
Finance     5000
HR          4000
Name: Salary, dtype: int64

In [112]:
df["dept_avg_salary"]=df.groupby("Department")["Salary"].transform("mean")
print(df)

   EmpID    Name Department Gender  Age  Salary  Experience    City  \
0    101    Riya         AI      F   23   45000           1  Indore
1    102   Rahul         HR      M   30   52000           5  Bhopal
2    103    Neha    Finance      F   28   60000           4  Indore
3    104    Amit         AI      M   35   70000           8   Delhi
4    105   Priya         HR      F   26   48000           2   Delhi
5    106   Karan    Finance      M   40   65000          10  Mumbai
6    107  Anjali         AI      F   29   55000           5  Indore
7    108   Rohit         HR      M   31   51000           6  Mumbai
8    109   Sneha    Finance      F   27   62000           3   Delhi
9    110   Arjun         AI      M   33   72000           9  Bhopal

  JoiningDate  rank  avg  dept_avg_salary
0  2023-01-10   1.0  NaN     60500.000000
1  2020-05-15   4.0  NaN     50333.333333
2  2021-03-20   6.0  NaN     62333.333333
3  2018-07-11   9.0  NaN     60500.000000
4  2022-06-18   2.0  NaN     50333.333333
5  2016-09-25   8.0  NaN     62333.333333
6  2020-11-05   5.0  NaN     60500.000000
7  2019-04-17   3.0  NaN     50333.333333
8  2021-12-01   7.0  NaN     62333.333333
9  2017-08-09  10.0  NaN     60500.000000

In [114]:
result=df.groupby("Department").filter(lambda x: len(x)>2)[["Name","Department"]]
print(result)

     Name Department
0    Riya         AI
1   Rahul         HR
2    Neha    Finance
3    Amit         AI
4   Priya         HR
5   Karan    Finance
6  Anjali         AI
7   Rohit         HR
8   Sneha    Finance
9   Arjun         AI